name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Copy .env example
        run: cp .env.example .env || true
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.11
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - name: Format  
        run: cargo fmt
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats